# Uncomment the next line to define a global platform for your project
# platform :ios, ‘9.0’

target ’Shadow’ do

pod 'GooglePlacePicker'
pod 'GooglePlaces'
 pod 'Alamofire', '~> 4.6'
pod 'RSKImageCropper'
pod ‘Charts’
pod 'ICGVideoTrimmer'
pod ‘QuickBlox’
use_frameworks!

end
